[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Circula"
authors = [{name = "Chaorong Chen", email = "c.chen@uci.edu"}]
dynamic = ["version", "description"]
